### ISSUE TITLE
Run CI nightly

### ISSUE THREAD

**Issue by mferrera** [equinor/xtgeoviz#14]
```yml
  schedule:
    # Run nightly to check that tests are working with latest dependencies
    - cron: "0 0 * * *"
 ```
